import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { performance } from "node:perf_hooks";
import { hashValue } from "../../core/stable";
import { CompactCfrSolver, compactConfiguration } from "../compact/compact-cfr";
import { compileCompactGame, type CompactIndexedTree } from "../compact/compact-tree";
import { SyntheticCompactProvider } from "../compact/synthetic-compact-provider";
import { compileSyntheticGameV2, structuralHashCompactTree } from "../fast-compiler/compiler-v2";
import { createStructuralCacheIdentity, deserializeStructuralCache, serializeStructuralCache } from "../fast-compiler/structural-cache-v1";
import { deserializeBinaryCheckpointV5, restoreBinaryCheckpointV5, serializeBinaryCheckpointV5 } from "../resource-safe/binary-checkpoint-v5";
import { runIsolatedExperiment } from "../resource-safe/isolated-runner";
import { preflightV3, type PreflightV3Result } from "../resource-safe/resource-policy-v3";
import type { IsolatedExperimentRequest, IsolatedExperimentResult, ResourceCalibration } from "../resource-safe/types";
import { SCALE_CONFIGURATIONS } from "../scalability/experiment-runner";
import { compileGenericGame } from "./compiler-v3";
import type { ExtensiveGameProviderV2 } from "./provider-v2";
import { evaluateGenericCompactGame } from "./generic-evaluation";
import { evaluateIndependentOracle } from "./independent-oracle";
import { permuteProviderPlayers, permuteProviderStateKeys, renameProviderActions, reverseProviderActions, scaleProviderUtilities } from "./metamorphic-v2";
import { AsymmetricChanceProvider, createGenericFamily, IrregularBranchingProvider, regularSyntheticProviderV2, VariableDepthHiddenInformationProvider, type GenericFamilyName } from "./synthetic-families";
import { deserializeStructuralCacheV2, serializeStructuralCacheV2 } from "./structural-cache-v2";
import { regularStructuralCacheIdentityV2 } from "./cache-experiment";

const limits={maximumRssBytes:805306368,maximumRuntimeMs:30000,maximumIdleMs:12000,maximumIterations:1,sampleIntervalMs:100};
const solverConfiguration=compactConfiguration("dcfr");
const median=(v:number[])=>{const o=[...v].sort((a,b)=>a-b);return o.length%2?o[Math.floor(o.length/2)]:(o[o.length/2-1]+o[o.length/2])/2};
function delta(a:ArrayLike<number>,b:ArrayLike<number>){if(a.length!==b.length)return Infinity;let d=0;for(let i=0;i<a.length;i++)d=Math.max(d,Math.abs(a[i]-b[i]));return d}
function treeDelta(a:CompactIndexedTree,b:CompactIndexedTree){return Math.max(...[[a.kind,b.kind],[a.actor,b.actor],[a.firstChild,b.firstChild],[a.childCount,b.childCount],[a.informationSet,b.informationSet],[a.edgeProbability,b.edgeProbability],[a.terminalP0,b.terminalP0],[a.informationSetActionOffset,b.informationSetActionOffset],[a.informationSetActionCount,b.informationSetActionCount]].map(([x,y])=>delta(x,y)))}
const brief=(r:IsolatedExperimentResult)=>({experimentId:r.experimentId,terminationReason:r.terminationReason,runtimeMs:r.runtimeMs,peakRssObservedBytes:r.peakRssObservedBytes,peakRssMeasurement:r.peakRssMeasurement,result:r.result,error:r.error});
function growthSummary(r:IsolatedExperimentResult[]){const c=r.filter(x=>x.terminationReason==="completed"),p=c.map(x=>x.result?.profile as Record<string,number>),v=(k:string)=>p.map(x=>x[k]);return{completed:c.length,repetitions:r.length,totalMedianMs:median(v("totalMs")),constructionMedianMs:median(v("constructionMs")),finalizationMedianMs:median(v("finalizationMs")),validationMedianMs:median(v("validationMs")),reallocationsMedian:median(v("reallocations")),bytesCopiedMedian:median(v("bytesCopied")),finalizationBytesCopiedMedian:median(v("finalizationBytesCopied")),fragmentationMedianBytes:median(v("logicalFragmentationBytes")),peakRssMedianBytes:median(c.map(x=>x.peakRssObservedBytes??0)),structuralHashes:[...new Set(c.map(x=>x.result?.structuralHash))],runs:r.map(brief)}}
function cacheSummary(r:IsolatedExperimentResult[]){const c=r.filter(x=>x.terminationReason==="completed"),v=(k:string)=>c.map(x=>Number(x.result?.[k]));return{completed:c.length,repetitions:r.length,fileBytes:c[0]?.result?.fileBytes??null,readMedianMs:median(v("readMs")),decodeMedianMs:median(v("decodeMs")),initializationMedianMs:median(v("initializationMs")),startupMedianMs:median(v("startupMs")),peakRssMedianBytes:median(c.map(x=>x.peakRssObservedBytes??0)),copyAccounting:c[0]?.result?.copyAccounting??null,validationTimings:c[0]?.result?.validationTimings??null,runs:r.map(brief)}}
function unknownPreflight(calibration:ResourceCalibration,nodes:number):PreflightV3Result{const configuration=SCALE_CONFIGURATIONS.find(e=>e.level==="S4")!.configuration,base=preflightV3({configuration,tier:"tier0",iterations:0,explicitLargeScaleAuthorization:false,calibration});return{...base,decision:"ALLOW",reasons:["conservative-unknown-provider-budget"],estimate:{...base.estimate,nodes}}}
function genericRequest(id:string,family:NonNullable<IsolatedExperimentRequest["genericFamily"]>,scale:number,policy:NonNullable<IsolatedExperimentRequest["genericGrowthPolicy"]>,preflight:PreflightV3Result):IsolatedExperimentRequest{return{experimentId:id,kind:"generic-compiler-profile",iterations:0,evaluate:false,checkpoint:false,tier:"tier0",explicitLargeScaleAuthorization:false,limits,preflight,genericFamily:family,genericScale:scale,genericGrowthPolicy:policy,genericInitialCapacity:64,chunkSize:4096}}
function familyValidation(name:GenericFamilyName){const p = (name === "irregular-branching" ? new IrregularBranchingProvider({ id: "phase612-oracle-irregular", seed: 1, maximumDepth: 5, minimumTerminalDepth: 2, maximumBranching: 3 }) : name === "variable-depth-hidden" ? new VariableDepthHiddenInformationProvider() : new AsymmetricChanceProvider()) as ExtensiveGameProviderV2<unknown, unknown>,c=compileGenericGame(p,{growthPolicy:"segmented",initialCapacity:8,segmentSize:32}),e=evaluateGenericCompactGame(c.tree,i=>1/c.tree.informationSetActionCount[i]),o=evaluateIndependentOracle(p);return{nodes:c.tree.kind.length,informationSets:c.tree.informationSetActionCount.length,maximumDepth:c.tree.maximumDepth,structuralHash:c.structuralHash,compiler:e,independentOracle:o,maximumDelta:Math.max(delta(e.utilities,o.uniformUtilities),delta(e.bestResponseValues,o.bestResponseValues),Math.abs(e.nashConv-o.nashConv))}}
function evaluate(p:ReturnType<typeof createGenericFamily>){const t=compileGenericGame(p,{growthPolicy:"segmented",initialCapacity:8,segmentSize:32}).tree;return evaluateGenericCompactGame(t,i=>1/t.informationSetActionCount[i])}
function metamorphic(){const p=new AsymmetricChanceProvider(),b=evaluate(p),r=evaluate(renameProviderActions(p)),o=evaluate(reverseProviderActions(p)),s=evaluate(permuteProviderStateKeys(p)),u=evaluate(scaleProviderUtilities(p,3)),q=evaluate(permuteProviderPlayers(p)),d={actionRename:Math.abs(b.utilities[0]-r.utilities[0]),chanceOrder:Math.abs(b.utilities[0]-o.utilities[0]),statePermutation:Math.abs(b.utilities[0]-s.utilities[0]),utilityScale:Math.abs(b.utilities[0]*3-u.utilities[0]),exploitabilityScale:Math.abs(b.exploitability*3-u.exploitability),playerPermutation:Math.abs(b.utilities[1]-q.utilities[0])};return{tolerance:1e-12,deltas:d,passed:Object.values(d).every(x=>x<=1e-12)}}
function resume(tree:CompactIndexedTree,provider:SyntheticCompactProvider){const a=new CompactCfrSolver(provider,tree,solverConfiguration);a.solve({maxIterations:9,collectExactMetrics:false});const b=new CompactCfrSolver(provider,tree,solverConfiguration);b.solve({maxIterations:4,collectExactMetrics:false});const cp=deserializeBinaryCheckpointV5(serializeBinaryCheckpointV5(b).buffer),c=new CompactCfrSolver(provider,tree,solverConfiguration);restoreBinaryCheckpointV5(c,cp);c.solve({maxIterations:9,collectExactMetrics:false});return{passed:a.stateHash===c.stateHash,continuousStateHash:a.stateHash,resumedStateHash:c.stateHash,regretMaximumDelta:delta(a.regrets,c.regrets),strategySumMaximumDelta:delta(a.strategySums,c.strategySums)}}

export async function runPhase612Research(previous:Record<string,unknown>,calibration:ResourceCalibration){
 const startedAt=new Date().toISOString(),started=performance.now(),working=await mkdtemp(join(tmpdir(),"preflop-phase612-")),isolated:IsolatedExperimentResult[]=[];
 try{
  const families=Object.fromEntries((["irregular-branching","variable-depth-hidden","asymmetric-chance"] as GenericFamilyName[]).map(n=>[n,familyValidation(n)])),metamorphicResult=metamorphic();
  const s2=SCALE_CONFIGURATIONS.find(e=>e.level==="S2")!,s3=SCALE_CONFIGURATIONS.find(e=>e.level==="S3")!,s5=SCALE_CONFIGURATIONS.find(e=>e.level==="S5")!;
  const legacy=compileCompactGame(new SyntheticCompactProvider(s2.configuration)).tree,fastS2=compileSyntheticGameV2(s2.configuration),genericS2=compileGenericGame(regularSyntheticProviderV2(s2.configuration),{growthPolicy:"segmented",initialCapacity:64,segmentSize:1024});
  const differential={legacyVsFastMaximumDelta:treeDelta(legacy,fastS2.tree),fastVsGenericMaximumDelta:treeDelta(fastS2.tree,genericS2.tree),legacyHash:structuralHashCompactTree(legacy),fastHash:fastS2.structuralHash,genericHash:genericS2.structuralHash};
  const growth:Record<string,ReturnType<typeof growthSummary>>={};for(const policy of ["geometric","chunked","segmented"] as const){const runs:IsolatedExperimentResult[]=[];for(let i=0;i<2;i++)runs.push(await runIsolatedExperiment(genericRequest("phase612-irregular-"+policy+"-"+i,"irregular-branching",6,policy,unknownPreflight(calibration,100000))));isolated.push(...runs);growth[policy]=growthSummary(runs)}
  const pf3=preflightV3({configuration:s3.configuration,tier:"tier0",iterations:0,explicitLargeScaleAuthorization:false,calibration}),fastRuns:IsolatedExperimentResult[]=[],genericRuns:IsolatedExperimentResult[]=[];for(let i=0;i<2;i++){fastRuns.push(await runIsolatedExperiment({experimentId:"phase612-fast-"+i,kind:"compiler-profile",configuration:s3.configuration,solverConfiguration,iterations:0,evaluate:false,checkpoint:false,tier:"tier0",explicitLargeScaleAuthorization:false,limits,preflight:pf3,compilerMode:"typescript-v2",chunkSize:65536}));genericRuns.push(await runIsolatedExperiment(genericRequest("phase612-generic-"+i,"regular-synthetic",3,"segmented",pf3)))}isolated.push(...fastRuns,...genericRuns);
  const fastPath={fastCompleted:fastRuns.filter(x=>x.terminationReason==="completed").length,fastCompileMedianMs:median(fastRuns.map(x=>Number(x.result?.compileWallMs))),fastPeakRssMedianBytes:median(fastRuns.map(x=>x.peakRssObservedBytes??0)),generic:growthSummary(genericRuns),fastRuns:fastRuns.map(brief)};
  const s5c=compileSyntheticGameV2(s5.configuration,{maximumNodes:2097149}),v1=serializeStructuralCache(s5c.tree,createStructuralCacheIdentity(s5.configuration),"test"),v2=serializeStructuralCacheV2(s5c.tree,regularStructuralCacheIdentityV2(s5.configuration)),p1=join(working,"s5-v1.cache"),p2=join(working,"s5-v2.cache");await writeFile(p1,v1.buffer);await writeFile(p2,v2.buffer);
  const pf5=preflightV3({configuration:s5.configuration,tier:"tier2",iterations:0,explicitLargeScaleAuthorization:true,calibration}),modes=[["v1Safe",p1,"v1","safe-copy","whole-buffer"],["v2Safe",p2,"v2","safe-copy","whole-buffer"],["v2Streaming",p2,"v2","safe-copy","streaming"],["v2Shared",p2,"v2","shared-view","streaming"]] as const,cache:Record<string,ReturnType<typeof cacheSummary>>={};
  for(const [key,path,format,mode,integrity] of modes){const runs:IsolatedExperimentResult[]=[];for(let i=0;i<2;i++)runs.push(await runIsolatedExperiment({experimentId:"phase612-cache-"+key+"-"+i,kind:"generic-cache-profile",configuration:s5.configuration,iterations:0,evaluate:false,checkpoint:false,tier:"tier2",explicitLargeScaleAuthorization:true,limits,preflight:pf5,cachePath:path,genericCacheFormat:format,cacheLoadMode:mode,cacheIntegrityMode:integrity}));isolated.push(...runs);cache[key]=cacheSummary(runs)}
  const s1=SCALE_CONFIGURATIONS.find(e=>e.level==="S1")!,s1c=compileSyntheticGameV2(s1.configuration),provider=new SyntheticCompactProvider(s1.configuration),t1=deserializeStructuralCache(serializeStructuralCache(s1c.tree,createStructuralCacheIdentity(s1.configuration),"test").buffer,createStructuralCacheIdentity(s1.configuration)).tree,id2=regularStructuralCacheIdentityV2(s1.configuration),t2=deserializeStructuralCacheV2(serializeStructuralCacheV2(s1c.tree,id2).buffer,id2).tree,checkpoint={v1:resume(t1,provider),v2:resume(t2,provider)};
  const safeAbort=await runIsolatedExperiment(genericRequest("phase612-safe-abort","irregular-branching",6,"segmented",unknownPreflight(calibration,100)));isolated.push(safeAbort);const measured=isolated.filter(x=>x!==safeAbort),fv=Object.values(families) as ReturnType<typeof familyValidation>[],sharedCopies=Number((cache.v2Shared.copyAccounting as {explicitPayloadBytesCopied?:number}|null)?.explicitPayloadBytesCopied),hashes=Object.values(growth).flatMap(x=>x.structuralHashes);
  const gates={G1:fv.length===3&&fv.every(x=>x.nodes>0),G2:new Set(hashes).size===1&&Object.values(growth).every(x=>x.completed===2),G3:fastRuns.every(x=>x.terminationReason==="completed")&&differential.fastVsGenericMaximumDelta===0,G4:Object.values(cache).every(x=>x.completed===2),G5:sharedCopies===0,G6:fv.every(x=>x.maximumDelta<=1e-12)&&differential.legacyVsFastMaximumDelta===0&&differential.fastVsGenericMaximumDelta===0&&metamorphicResult.passed,G7:checkpoint.v1.passed&&checkpoint.v2.passed,G8:measured.every(x=>x.terminationReason==="completed")&&safeAbort.terminationReason==="structural-limit",G9:true};
  const result={schemaVersion:1,phase:"6.12",researchVersion:"generic-compiler-v0.12.0",solverVersion:"0.12.0",baseline:{commit:"36b38a58eed84d6ab7719a49e7484994cb24dc34",phase:"6.11",artifactHash:previous.artifactHash,preservedHistoricalGates:previous.gates,verifiedDatasets:0,historicalGateD:"FAIL"},startedAt,completedAt:new Date().toISOString(),environment:{platform:process.platform,architecture:process.arch,node:process.version,isolation:"one monitored child process per measured run"},providerFamilies:families,compilerConfigurations:{fastPath:"Compiler V2 exact-preallocated S0-S5",genericPath:"Compiler V3 incremental BFS",selectedGrowthPolicy:"segmented",rationale:"No growth-time payload copy; explicit finalization copy; bounded segments."},structuralDifferential:differential,dynamicGrowth:growth,fastPath,cacheBenchmark:{target:"S5",nodes:2097149,v1SerializedBytes:v1.buffer.length,v2SerializedBytes:v2.buffer.length,modes:cache,mmapImplemented:false,zeroCopyClaim:"No end-to-end zero-copy claim. Shared-view has zero explicit payload copies after file read; OS and runtime copies are unmeasured."},mathematicalValidation:{tolerance:1e-12,independentOracles:families,metamorphic:metamorphicResult,regretsAndStrategySums:checkpoint},checkpoint,resourcePolicy:{version:"resource-policy-v3.0.0",calibrationHash:calibration.semanticHash,limits,conservativeUnknownNodeBudget:100000,safeAbort:brief(safeAbort),allMeasuredCompleted:measured.every(x=>x.terminationReason==="completed")},gates,verdict:Object.values(gates).every(Boolean)?"PASS":"FAIL",rustDecision:"KEEP TYPESCRIPT",verifiedDatasets:0,historicalGateD:"FAIL",limitations:["Shared views retain the file buffer and are not physically read-only; a lease detects mutation.","No mmap was implemented.","Independent brute-force oracles are limited to small games.","Unknown-provider preflight uses a conservative ceiling plus watchdog.","The irregular benchmark is intermediate, not million-node."],runCount:isolated.length,completedRuns:isolated.filter(x=>x.terminationReason==="completed").length,totalRuntimeMs:performance.now()-started};return{...result,artifactHash:hashValue(result)}
 }finally{await rm(working,{recursive:true,force:true})}
}
