"use client";

import Link from "next/link";
import { useCallback, useEffect, useEffectEvent, useMemo, useState, type ReactNode } from "react";
import type { ConsoleRunDetails, ConsoleRunSummary, ConsoleTree } from "../../solver/research/console/contracts";
import type { ResearchExperimentConfigurationV1 } from "../../solver/research/public/contracts";
import {
  ConvergenceChart, Dialog, EmptyState, ErrorState, formatBytes, formatDuration, Loading, MetricCard, ProgressBar,
  StatusBadge, Toasts, ValidationBadge, type Toast,
} from "./components";
import { ConsoleApiError, researchApi, subscribeToRun } from "./client";

type PathState = { section: string; id?: string };
type Remote<T> = { loading: boolean; value: T | null; error: Error | null };

const NAVIGATION = [
  ["overview", "Overview", "â—«"], ["experiments", "Experiments", "âŒ"], ["new", "New Experiment", "+"],
  ["algorithms", "Algorithms", "Æ’"], ["games", "Game Explorer", "â—‡"], ["results", "Results", "âˆ¿"],
  ["checkpoints", "Checkpoints", "â—‰"], ["diagnostics", "Diagnostics", "âŒ˜"], ["settings", "Settings", "âš™"],
] as const;

function parsePath(parts: string[]): PathState {
  if (!parts.length) return { section: "overview" };
  if ((parts[0] === "experiments" || parts[0] === "results") && parts[1]) return { section: parts[0], id: parts[1] };
  return { section: NAVIGATION.some(([key]) => key === parts[0]) ? parts[0] : "overview" };
}

function useRemote<T>(load: () => Promise<T>, keys: readonly unknown[] = []): Remote<T> & { reload: () => void } {
  const [revision, setRevision] = useState(0);
  const [state, setState] = useState<Remote<T>>({ loading: true, value: null, error: null });
  const runLoad = useEffectEvent(load);
  const key = JSON.stringify(keys);
  useEffect(() => {
    let current = true;
    void runLoad().then((value) => { if (current) setState({ loading: false, value, error: null }); }).catch((error: Error) => { if (current) setState({ loading: false, value: null, error }); });
    return () => { current = false; };
  }, [key, revision]);
  return { ...state, reload: () => { setState((previous) => ({ ...previous, loading: true, error: null })); setRevision((value) => value + 1); } };
}

function SectionTitle({ eyebrow, title, copy, actions }: { eyebrow: string; title: string; copy: string; actions?: ReactNode }) {
  return <header className="rc-section-title"><div><span>{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div>{actions && <div className="rc-title-actions">{actions}</div>}</header>;
}

function RunTable({ runs, empty = "Nenhum experimento encontrado." }: { runs: ConsoleRunSummary[]; empty?: string }) {
  if (!runs.length) return <EmptyState title="Sem dados" copy={empty} action={<Link className="rc-button rc-button-primary" href="/research/new">Criar experimento</Link>} />;
  return <div className="rc-table-scroll"><table className="rc-table"><thead><tr><th>Experimento</th><th>Status</th><th>Algoritmo</th><th>Jogo</th><th>Progresso</th><th>Atualizado</th><th><span className="sr-only">AÃ§Ãµes</span></th></tr></thead><tbody>{runs.map((run) => <tr key={run.runId}><td><strong>{run.experimentId}</strong><small>{run.runId.slice(-12)}</small></td><td><StatusBadge state={run.state} /></td><td>{algorithmLabel(run.algorithm)}</td><td>{providerLabel(run.provider)}</td><td><div className="rc-progress-cell"><ProgressBar value={run.progress} /><span>{run.completedIterations}/{run.iterations}</span></div></td><td>{new Date(run.updatedAt).toLocaleString("pt-BR")}</td><td><Link className="rc-row-link" href={`/research/experiments/${encodeURIComponent(run.runId)}`} aria-label={`Abrir ${run.experimentId}`}>â†’</Link></td></tr>)}</tbody></table></div>;
}

function algorithmLabel(id: string) { return id === "vanilla-cfr" ? "Vanilla CFR" : id === "cfr-plus" ? "CFR+" : "DCFR"; }
function providerLabel(id: string) { return ({ "variable-depth-hidden": "Variable Depth", "asymmetric-chance": "Asymmetric Chance", "irregular-branching": "Irregular Branching", "regular-synthetic": "Regular Synthetic" } as Record<string, string>)[id] ?? id; }
function metric(value: number | null | undefined, digits = 5) { return value === null || value === undefined ? "â€”" : value.toPrecision(digits); }

function Overview() {
  const data = useRemote(() => researchApi.overview(), []);
  if (data.loading && !data.value) return <Loading rows={7} />;
  if (data.error || !data.value) return <ErrorState error={data.error ?? new Error("Overview indisponÃ­vel.")} retry={data.reload} />;
  const value = data.value;
  return <><SectionTitle eyebrow="Research Engine 1.0.0" title="VisÃ£o geral do laboratÃ³rio" copy="Estado real do ambiente, das execuÃ§Ãµes sintÃ©ticas e dos artefatos persistidos." actions={<Link className="rc-button rc-button-primary" href="/research/new">+ Novo experimento</Link>} />
    <div className="rc-health-line"><StatusBadge state={value.environment.status} /><span>Engine {value.capabilities.engineVersion}</span><span>{value.capabilities.capabilities.length} capabilities</span><span>2 jogadores Â· soma zero Â· escopo sintÃ©tico</span></div>
    <section className="rc-metric-grid"><MetricCard label="Experimentos" value={value.totals.all} detail="persistidos" /><MetricCard label="ConcluÃ­dos" value={value.totals.completed} tone="green" detail="com resultado Ã­ntegro" /><MetricCard label="Em execuÃ§Ã£o" value={value.totals.running} tone="amber" detail={`${value.resources.activeRuns} neste processo`} /><MetricCard label="Interrompidos" value={value.totals.interrupted} detail="cancelados ou recuperÃ¡veis" /><MetricCard label="Falhas" value={value.totals.failed} tone={value.totals.failed ? "red" : "default"} detail="com cÃ³digo estruturado" /></section>
    <div className="rc-two-columns"><section className="rc-panel"><div className="rc-panel-head"><div><span>ATIVIDADE</span><h2>Ãšltimas execuÃ§Ãµes</h2></div><Link href="/research/experiments">Ver todas</Link></div><RunTable runs={value.recentRuns} /></section><section className="rc-panel rc-environment"><div className="rc-panel-head"><div><span>AMBIENTE</span><h2>SeguranÃ§a operacional</h2></div></div><dl><div><dt>Processos ativos</dt><dd>{value.resources.activeRuns}</dd></div><div><dt>Ãšltimo pico RSS</dt><dd>{formatBytes(value.resources.peakRssBytes)}</dd></div><div><dt>Ãšltimo runtime</dt><dd>{formatDuration(value.resources.runtimeMs)}</dd></div><div><dt>Gate D</dt><dd className="rc-danger-text">FAIL</dd></div><div><dt>Datasets Verified</dt><dd>0</dd></div></dl><p className="rc-scope-note">Resultados do console validam jogos sintÃ©ticos finitos. Eles nÃ£o certificam ranges nem estratÃ©gias de poker.</p></section></div>
    {value.recentFailures.length > 0 && <section className="rc-panel"><div className="rc-panel-head"><div><span>ATENÃ‡ÃƒO</span><h2>Falhas recentes</h2></div></div><RunTable runs={value.recentFailures} /></section>}
  </>;
}

function Experiments() {
  const [search, setSearch] = useState(""); const [state, setState] = useState("all"); const [sort, setSort] = useState("newest"); const [page, setPage] = useState(1);
  const query = useMemo(() => new URLSearchParams({ search, state, sort, page: String(page), pageSize: "10" }).toString(), [search, state, sort, page]);
  const data = useRemote(() => researchApi.experiments(query), [query]);
  return <><SectionTitle eyebrow="Experiment Management" title="Experimentos" copy="Busque e acompanhe execuÃ§Ãµes persistidas pelo Research Engine." actions={<Link className="rc-button rc-button-primary" href="/research/new">+ Novo experimento</Link>} />
    <section className="rc-panel"><div className="rc-filters"><label><span>Buscar</span><input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="ID, jogo ou algoritmo" /></label><label><span>Status</span><select value={state} onChange={(event) => { setState(event.target.value); setPage(1); }}><option value="all">Todos</option>{["created", "running", "completed", "cancelled", "interrupted", "failed"].map((value) => <option key={value}>{value}</option>)}</select></label><label><span>Ordenar</span><select value={sort} onChange={(event) => setSort(event.target.value)}><option value="newest">Mais recentes</option><option value="oldest">Mais antigos</option></select></label></div>
      {data.loading && !data.value ? <Loading rows={5} /> : data.error ? <ErrorState error={data.error} retry={data.reload} /> : <><RunTable runs={data.value?.items ?? []} /><div className="rc-pagination"><button disabled={page === 1} onClick={() => setPage((value) => value - 1)}>â† Anterior</button><span>PÃ¡gina {page} Â· {data.value?.total ?? 0} registros</span><button disabled={(data.value?.items.length ?? 0) < 10} onClick={() => setPage((value) => value + 1)}>PrÃ³xima â†’</button></div></>}
    </section></>;
}

const INITIAL_CONFIGURATION: ResearchExperimentConfigurationV1 = {
  schemaVersion: "research-experiment-v1", provider: { id: "variable-depth-hidden" }, algorithm: { id: "dcfr", seed: 7000, dcfr: { alpha: 1.5, beta: 0, gamma: 2 } },
  budget: { iterations: 10, runtimeMs: 10_000, memoryBytes: 256 * 1024 * 1024, tier: "tier0" }, evaluation: { interval: 2, exact: true }, checkpoint: { interval: 5, retain: 2 },
  outputDirectory: ".preflop-research/runs", validation: { structural: true, independentEvaluation: true },
};

function NewExperiment({ navigate, notify }: { navigate: (path: string) => void; notify: (message: string, tone?: Toast["tone"]) => void }) {
  const [step, setStep] = useState(1); const [configuration, setConfiguration] = useState(INITIAL_CONFIGURATION); const [validation, setValidation] = useState<unknown>(null); const [error, setError] = useState<Error | null>(null); const [busy, setBusy] = useState(false);
  const update = (patch: Partial<ResearchExperimentConfigurationV1>) => setConfiguration((value) => ({ ...value, ...patch }));
  const next = async () => { setError(null); if (step === 7) { setBusy(true); try { setValidation(await researchApi.validate(configuration)); } catch (caught) { setError(caught as Error); return; } finally { setBusy(false); } } setStep((value) => Math.min(8, value + 1)); };
  const execute = async () => { setBusy(true); setError(null); try { await researchApi.validate(configuration); const handle = await researchApi.create(configuration); await researchApi.action(handle.runId, "run"); notify("Experimento criado e aceito pelo engine.", "success"); navigate(`/research/experiments/${handle.runId}`); } catch (caught) { setError(caught as Error); } finally { setBusy(false); } };
  const steps = ["Jogo", "Algoritmo", "ParÃ¢metros", "OrÃ§amento", "AvaliaÃ§Ã£o", "Checkpoints", "Validar", "Executar"];
  return <><SectionTitle eyebrow="Guided Experiment" title="Novo experimento" copy="Configure um jogo sintÃ©tico usando exatamente o schema Experiment V1." />
    <div className="rc-wizard-layout"><ol className="rc-steps">{steps.map((label, index) => <li key={label} className={step === index + 1 ? "active" : step > index + 1 ? "done" : ""}><button onClick={() => index + 1 < step && setStep(index + 1)}><i>{step > index + 1 ? "âœ“" : index + 1}</i><span>{label}</span></button></li>)}</ol>
      <section className="rc-panel rc-wizard"><div className="rc-wizard-head"><span>ETAPA {step} DE 8</span><h2>{steps[step - 1]}</h2></div>
        {step === 1 && <div className="rc-card-options">{(["variable-depth-hidden", "asymmetric-chance", "irregular-branching", "regular-synthetic"] as const).map((id) => <button key={id} className={configuration.provider.id === id ? "selected" : ""} onClick={() => update({ provider: { id } })}><strong>{providerLabel(id)}</strong><span>{id === "regular-synthetic" ? "Ãrvore regular com fast compiler V2." : id === "irregular-branching" ? "Profundidade e branching irregulares." : id === "asymmetric-chance" ? "Eventos de chance com probabilidades assimÃ©tricas." : "InformaÃ§Ã£o oculta e profundidade variÃ¡vel."}</span></button>)}</div>}
        {step === 2 && <div className="rc-card-options rc-algorithm-options">{(["vanilla-cfr", "cfr-plus", "dcfr"] as const).map((id) => <button key={id} className={configuration.algorithm.id === id ? "selected" : ""} onClick={() => update({ algorithm: { ...configuration.algorithm, id, ...(id === "dcfr" ? { dcfr: configuration.algorithm.dcfr ?? { alpha: 1.5, beta: 0, gamma: 2 } } : {}) } })}><strong>{algorithmLabel(id)}</strong><span>{id === "vanilla-cfr" ? "ReferÃªncia clÃ¡ssica: minimiza arrependimento ao longo das iteraÃ§Ãµes." : id === "cfr-plus" ? "Trunca arrependimentos negativos e usa atraso de mÃ©dia configurÃ¡vel." : "Aplica descontos separados a arrependimentos e estratÃ©gia acumulada."}</span></button>)}</div>}
        {step === 3 && <div className="rc-form-grid"><label><span>Seed</span><input type="number" min={0} max={4294967295} value={configuration.algorithm.seed} onChange={(event) => update({ algorithm: { ...configuration.algorithm, seed: Number(event.target.value) } })} /><small>Controla a sequÃªncia determinÃ­stica do experimento.</small></label>{configuration.algorithm.id === "cfr-plus" && <label><span>Atraso da mÃ©dia</span><input type="number" min={0} value={configuration.algorithm.cfrPlusAveragingDelay ?? 0} onChange={(event) => update({ algorithm: { ...configuration.algorithm, cfrPlusAveragingDelay: Number(event.target.value) } })} /><small>IteraÃ§Ãµes antes de acumular a estratÃ©gia mÃ©dia.</small></label>}{configuration.algorithm.id === "dcfr" && <>{(["alpha", "beta", "gamma"] as const).map((key) => <label key={key}><span>DCFR {key}</span><input type="number" step="0.1" value={configuration.algorithm.dcfr?.[key] ?? 0} onChange={(event) => update({ algorithm: { ...configuration.algorithm, dcfr: { ...(configuration.algorithm.dcfr ?? { alpha: 1.5, beta: 0, gamma: 2 }), [key]: Number(event.target.value) } } })} /><small>{key === "alpha" ? "Desconto de arrependimento positivo." : key === "beta" ? "Desconto de arrependimento negativo." : "Peso da estratÃ©gia acumulada."}</small></label>)}</>}</div>}
        {step === 4 && <div className="rc-form-grid"><label><span>Iteration budget</span><input type="number" min={1} max={20} value={configuration.budget.iterations} onChange={(event) => update({ budget: { ...configuration.budget, iterations: Number(event.target.value) } })} /><small>Tier 0 pÃºblico: atÃ© 20 iteraÃ§Ãµes.</small></label><label><span>Runtime budget (ms)</span><input type="number" min={1} max={30000} value={configuration.budget.runtimeMs} onChange={(event) => update({ budget: { ...configuration.budget, runtimeMs: Number(event.target.value) } })} /><small>MÃ¡ximo autorizado: 30.000 ms.</small></label><label><span>Memory budget (MiB)</span><input type="number" min={64} max={768} value={Math.round(configuration.budget.memoryBytes / 1024 / 1024)} onChange={(event) => update({ budget: { ...configuration.budget, memoryBytes: Number(event.target.value) * 1024 * 1024 } })} /><small>O watchdog tambÃ©m observa RSS real.</small></label><label><span>Tier</span><select value={configuration.budget.tier} onChange={(event) => update({ budget: { ...configuration.budget, tier: event.target.value as "tier0" } })}><option value="tier0">Tier 0 Â· pÃºblico e calibrado</option></select><small>Tiers superiores nÃ£o sÃ£o liberados pelo console sem contrato calibrado.</small></label></div>}
        {step === 5 && <div className="rc-form-grid"><label><span>Intervalo de avaliaÃ§Ã£o</span><input type="number" min={1} max={configuration.budget.iterations} value={configuration.evaluation.interval} onChange={(event) => update({ evaluation: { ...configuration.evaluation, interval: Number(event.target.value) } })} /><small>FrequÃªncia de pontos reais na curva.</small></label><div className="rc-check"><input id="evaluation-exact" aria-label="AvaliaÃ§Ã£o exata" type="checkbox" checked={configuration.evaluation.exact} onChange={(event) => update({ evaluation: { ...configuration.evaluation, exact: event.target.checked } })} /><span><strong>AvaliaÃ§Ã£o exata</strong><small>Calcula best response e NashConv quando suportado.</small></span></div><div className="rc-check"><input id="validation-independent" aria-label="Cross-check independente" type="checkbox" checked={configuration.validation.independentEvaluation} onChange={(event) => update({ validation: { ...configuration.validation, independentEvaluation: event.target.checked } })} /><span><strong>Cross-check independente</strong><small>Compara com o orÃ¡culo separado em jogos pequenos.</small></span></div></div>}
        {step === 6 && <div className="rc-form-grid"><label><span>Intervalo de checkpoint</span><input type="number" min={1} max={configuration.budget.iterations} value={configuration.checkpoint.interval} onChange={(event) => update({ checkpoint: { ...configuration.checkpoint, interval: Number(event.target.value) } })} /><small>Cria Checkpoint V5 nesta frequÃªncia.</small></label><label><span>GeraÃ§Ãµes retidas</span><input type="number" min={1} max={16} value={configuration.checkpoint.retain} onChange={(event) => update({ checkpoint: { ...configuration.checkpoint, retain: Number(event.target.value) } })} /><small>Entre 1 e 16 geraÃ§Ãµes Ã­ntegras.</small></label></div>}
        {step === 7 && <div className="rc-review"><p>O prÃ³ximo passo envia esta configuraÃ§Ã£o ao validator real. Nenhum diretÃ³rio ou processo Ã© criado durante a validaÃ§Ã£o.</p><pre>{JSON.stringify(configuration, null, 2)}</pre></div>}
        {step === 8 && <div className="rc-review">{validation ? <><div className="rc-validation-ok">âœ“ ConfiguraÃ§Ã£o aceita pela API pÃºblica e pelo Resource Policy.</div><pre>{JSON.stringify(validation, null, 2)}</pre></> : <p>A validaÃ§Ã£o precisa ser concluÃ­da antes da execuÃ§Ã£o.</p>}</div>}
        {error && <ErrorState error={error} />}
        <div className="rc-wizard-actions"><button className="rc-button rc-button-ghost" disabled={step === 1 || busy} onClick={() => setStep((value) => value - 1)}>â† Voltar</button>{step < 8 ? <button className="rc-button rc-button-primary" disabled={busy} onClick={() => void next()}>{busy ? "Validandoâ€¦" : step === 7 ? "Validar no engine" : "Continuar â†’"}</button> : <button className="rc-button rc-button-primary" disabled={busy || !validation} onClick={() => void execute()}>{busy ? "Criandoâ€¦" : "Executar experimento"}</button>}</div>
      </section></div></>;
}

function Algorithms() {
  const data = useRemote(() => researchApi.capabilities(), []);
  return <><SectionTitle eyebrow="Algorithm Registry" title="Algoritmos" copy="ImplementaÃ§Ãµes do Research Engine e os parÃ¢metros que controlam cada execuÃ§Ã£o." />{data.loading ? <Loading rows={4} /> : data.error ? <ErrorState error={data.error} retry={data.reload} /> : <div className="rc-algorithm-grid">{data.value?.algorithms.map((algorithm) => <article className="rc-panel" key={algorithm.id}><span className="rc-kicker">{algorithm.version}</span><h2>{algorithmLabel(algorithm.id)}</h2><p>{algorithm.id === "vanilla-cfr" ? "Baseline canÃ´nica de Counterfactual Regret Minimization. Ãštil como referÃªncia transparente para comparaÃ§Ãµes." : algorithm.id === "cfr-plus" ? "CFR com arrependimentos negativos truncados e mÃ©dia atrasada. Frequentemente converge mais rÃ¡pido, sem mudar o jogo." : "Discounted CFR: controla separadamente o peso do passado em arrependimentos positivos, negativos e na estratÃ©gia mÃ©dia."}</p><dl><div><dt>Checkpoint</dt><dd>V{algorithm.checkpointVersion}</dd></div><div><dt>ExecuÃ§Ã£o</dt><dd>Processo isolado</dd></div><div><dt>ValidaÃ§Ã£o</dt><dd>Fase 6.13 diferencial</dd></div></dl><Link className="rc-button rc-button-ghost" href="/research/new">Configurar {algorithmLabel(algorithm.id)}</Link></article>)}</div>}</>;
}

function GameExplorer() {
  const games = useRemote(() => researchApi.games(), []); const [selected, setSelected] = useState<string | null>(null);
  const activeSelection = selected ?? games.value?.[0]?.selectionId ?? null;
  const tree = useRemote(() => activeSelection ? researchApi.tree(activeSelection) : Promise.resolve(null as ConsoleTree | null), [activeSelection]);
  const game = games.value?.find((item) => item.selectionId === activeSelection) ?? games.value?.[0];
  return <><SectionTitle eyebrow="Synthetic Game Registry" title="Game Explorer" copy="Estruturas compiladas e validadas pelo engine. A Ã¡rvore Ã© limitada para preservar responsividade." />{games.loading ? <Loading rows={5} /> : games.error ? <ErrorState error={games.error} retry={games.reload} /> : <div className="rc-explorer-layout"><aside className="rc-game-list">{games.value?.map((item) => <button className={activeSelection === item.selectionId ? "selected" : ""} onClick={() => setSelected(item.selectionId)} key={item.selectionId}><strong>{providerLabel(item.selectionId)}</strong><span>{item.nodes} nodes Â· {item.compiler}</span></button>)}</aside>{game && <section className="rc-panel"><div className="rc-game-title"><div><span>GAME ID</span><h2>{game.id}</h2><p>{game.structuralHash}</p></div><span className={game.validation.valid ? "rc-valid" : "rc-invalid"}>{game.validation.valid ? "VALID" : "INVALID"}</span></div><div className="rc-stat-strip"><div><strong>{game.nodes}</strong><span>nodes</span></div><div><strong>{game.informationSets}</strong><span>infosets</span></div><div><strong>{game.chanceNodes}</strong><span>chance</span></div><div><strong>{game.terminalNodes}</strong><span>terminais</span></div></div><div className="rc-capabilities">{game.capabilities.map((item) => <span key={item}>{item}</span>)}</div><h3 className="rc-subtitle">Ãrvore progressiva</h3>{tree.loading ? <Loading rows={4} /> : tree.error ? <ErrorState error={tree.error} retry={tree.reload} /> : tree.value && <GameTree tree={tree.value} />}</section>}</div>}</>;
}

function GameTree({ tree }: { tree: ConsoleTree }) {
  const depths = [...new Set(tree.nodes.map((node) => node.depth))];
  return <div className="rc-tree" role="tree" aria-label={`Ãrvore de ${tree.gameId}`}>{depths.map((depth) => <div className="rc-tree-level" key={depth}><span>NÃVEL {depth}</span><div>{tree.nodes.filter((node) => node.depth === depth).map((node) => <button key={node.id} role="treeitem" aria-selected="false" className={`rc-tree-node rc-tree-${node.kind}`} title={node.informationSet ?? node.utility?.join(" / ") ?? node.action ?? node.kind}><i>{node.kind === "chance" ? "â—‡" : node.kind === "terminal" ? "â– " : node.actor === 0 ? "P0" : "P1"}</i><strong>{node.action ?? "root"}</strong>{node.chanceProbability !== null && <small>p {node.chanceProbability.toFixed(3)}</small>}</button>)}</div></div>)}{tree.truncated && <p className="rc-scope-note">VisualizaÃ§Ã£o limitada a {tree.limit} nÃ³s. As estatÃ­sticas acima cobrem a Ã¡rvore completa.</p>}</div>;
}

function Results() {
  const data = useRemote(() => researchApi.experiments(new URLSearchParams({ state: "completed", pageSize: "50" }).toString()), []);
  const [selected, setSelected] = useState<string[]>([]); const [details, setDetails] = useState<ConsoleRunDetails[]>([]); const [warning, setWarning] = useState("");
  useEffect(() => { let current = true; if (selected.length < 2) return; void Promise.all(selected.map((id) => researchApi.experiment(id))).then((values) => { if (!current) return; setDetails(values); const first = values[0].configuration; setWarning(values.some((value) => value.configuration.provider.id !== first.provider.id || value.configuration.budget.iterations !== first.budget.iterations) ? "As configuraÃ§Ãµes nÃ£o sÃ£o diretamente comparÃ¡veis: jogo ou orÃ§amento de iteraÃ§Ãµes difere." : ""); }); return () => { current = false; }; }, [selected]);
  const colors = ["#b9f45b", "#6de0c2", "#ffb45f"];
  return <><SectionTitle eyebrow="Results & Comparison" title="Resultados" copy="Artefatos completos, curvas reais e comparaÃ§Ã£o de execuÃ§Ãµes equivalentes." />{data.loading ? <Loading rows={5} /> : data.error ? <ErrorState error={data.error} retry={data.reload} /> : !(data.value?.items.length) ? <EmptyState title="Nenhum resultado" copy="Conclua um experimento para visualizar mÃ©tricas e curvas reais." action={<Link className="rc-button rc-button-primary" href="/research/new">Criar experimento</Link>} /> : <><section className="rc-panel"><div className="rc-panel-head"><div><span>SELEÃ‡ÃƒO</span><h2>Comparar algoritmos</h2></div><small>Escolha 2 ou 3 resultados</small></div><div className="rc-result-selector">{data.value.items.map((run) => <label key={run.runId}><input type="checkbox" checked={selected.includes(run.runId)} disabled={!selected.includes(run.runId) && selected.length >= 3} onChange={(event) => setSelected((items) => event.target.checked ? [...items, run.runId] : items.filter((id) => id !== run.runId))} /><span><strong>{algorithmLabel(run.algorithm)}</strong><small>{run.experimentId} Â· {providerLabel(run.provider)}</small></span><Link href={`/research/results/${run.runId}`}>Abrir</Link></label>)}</div></section>{warning && <div className="rc-warning" role="status">âš  {warning}</div>}{details.length >= 2 && <section className="rc-panel"><div className="rc-panel-head"><div><span>CONVERGENCE</span><h2>NashConv comparado</h2></div></div><ConvergenceChart metric="nashConv" xAxis="iteration" scale="log" series={details.map((item, index) => ({ label: algorithmLabel(item.summary.algorithm), color: colors[index], rows: item.result?.convergence ?? [] }))} /><div className="rc-comparison-table">{details.map((item, index) => <article key={item.summary.runId} style={{ borderColor: colors[index] }}><strong>{algorithmLabel(item.summary.algorithm)}</strong><dl><div><dt>NashConv</dt><dd>{metric(item.result?.metrics.nashConv)}</dd></div><div><dt>Exploitability</dt><dd>{metric(item.result?.metrics.exploitability)}</dd></div><div><dt>Runtime</dt><dd>{formatDuration(item.result?.metrics.runtimeMs)}</dd></div><div><dt>Throughput</dt><dd>{item.result ? Math.round(item.result.metrics.nodesVisited / Math.max(1, item.result.metrics.runtimeMs) * 1000).toLocaleString("pt-BR") : "â€”"} nodes/s</dd></div><div><dt>Pico RSS</dt><dd>{formatBytes(item.result?.metrics.peakRssBytes)}</dd></div></dl></article>)}</div></section>}</>}</>;
}

function Checkpoints() {
  const list = useRemote(() => researchApi.experiments("pageSize=50"), []); const [details, setDetails] = useState<ConsoleRunDetails[]>([]);
  useEffect(() => { let current = true; if (list.value) void Promise.all(list.value.items.map((item) => researchApi.experiment(item.runId))).then((values) => { if (current) setDetails(values.filter((item) => item.checkpoints.length)); }); return () => { current = false; }; }, [list.value]);
  return <><SectionTitle eyebrow="Checkpoint V5" title="Checkpoints" copy="GeraÃ§Ãµes persistidas, integridade declarada pelo artefato e elegibilidade para recuperaÃ§Ã£o." />{list.loading ? <Loading rows={5} /> : list.error ? <ErrorState error={list.error} retry={list.reload} /> : !details.length ? <EmptyState title="Nenhum checkpoint" copy="Checkpoints Ã­ntegros aparecerÃ£o aqui apÃ³s uma execuÃ§Ã£o atingir o intervalo configurado." /> : <div className="rc-checkpoint-grid">{details.flatMap((run) => run.checkpoints.map((checkpoint) => <article className="rc-panel" key={`${run.summary.runId}-${checkpoint.file}`}><span className="rc-kicker">CHECKPOINT V5</span><h2>{run.summary.experimentId}</h2><code>{checkpoint.file}</code><dl><div><dt>IteraÃ§Ã£o</dt><dd>{checkpoint.iteration ?? "â€”"}</dd></div><div><dt>Tamanho</dt><dd>{formatBytes(checkpoint.sizeBytes)}</dd></div><div><dt>Modificado</dt><dd>{new Date(checkpoint.modifiedAt).toLocaleString("pt-BR")}</dd></div><div><dt>Compatibilidade</dt><dd>{["cancelled", "interrupted", "failed"].includes(run.summary.state) ? "ElegÃ­vel para restore" : "Preservado"}</dd></div></dl><Link className="rc-button rc-button-ghost" href={`/research/experiments/${run.summary.runId}`}>Inspecionar execuÃ§Ã£o</Link></article>))}</div>}</>;
}

function Diagnostics() {
  const doctor = useRemote(() => researchApi.doctor(), []); const capabilities = useRemote(() => researchApi.capabilities(), []); const [copied, setCopied] = useState(false);
  const payload = JSON.stringify({ doctor: doctor.value, capabilities: capabilities.value }, null, 2);
  return <><SectionTitle eyebrow="Environment Doctor" title="DiagnÃ³sticos" copy="VersÃµes, capabilities, limites e checks estruturados do ambiente local." actions={<button className="rc-button rc-button-ghost" disabled={!doctor.value} onClick={() => void navigator.clipboard.writeText(payload).then(() => setCopied(true))}>{copied ? "Copiado âœ“" : "Copiar diagnÃ³stico"}</button>} />{doctor.loading || capabilities.loading ? <Loading rows={6} /> : doctor.error ? <ErrorState error={doctor.error} retry={doctor.reload} /> : capabilities.error ? <ErrorState error={capabilities.error} retry={capabilities.reload} /> : <div className="rc-diagnostics-grid"><section className="rc-panel"><span className="rc-kicker">RUNTIME</span><h2>Research Engine</h2><pre>{JSON.stringify(doctor.value, null, 2)}</pre></section><section className="rc-panel"><span className="rc-kicker">CAPABILITY NEGOTIATION</span><h2>{capabilities.value?.capabilities.length} capacidades</h2><div className="rc-capabilities">{capabilities.value?.capabilities.map((item) => <span key={item}>{item}</span>)}</div><dl><div><dt>Players</dt><dd>{capabilities.value?.scope.players}</dd></div><div><dt>Zero-sum</dt><dd>Sim</dd></div><div><dt>Multiplayer</dt><dd>NÃ£o</dd></div><div><dt>Poker certificado</dt><dd>NÃ£o</dd></div></dl></section></div>}</>;
}

function Settings() {
  const [theme, setTheme] = useState(() => typeof window === "undefined" ? "dark" : localStorage.getItem("research-theme") ?? "dark");
  const [scale, setScale] = useState(() => typeof window === "undefined" ? "linear" : localStorage.getItem("research-chart-scale") ?? "linear");
  const [confirmCancel, setConfirmCancel] = useState(() => typeof window === "undefined" ? true : localStorage.getItem("research-confirm-cancel") !== "false");
  useEffect(() => { localStorage.setItem("research-theme", theme); localStorage.setItem("research-chart-scale", scale); localStorage.setItem("research-confirm-cancel", String(confirmCancel)); }, [theme, scale, confirmCancel]);
  return <><SectionTitle eyebrow="Local Preferences" title="Settings" copy="PreferÃªncias deste dispositivo. PolÃ­ticas obrigatÃ³rias do engine nÃ£o podem ser enfraquecidas aqui." /><div className="rc-settings-grid"><section className="rc-panel"><h2>AparÃªncia e grÃ¡ficos</h2><label><span>Tema</span><select value={theme} onChange={(event) => setTheme(event.target.value)}><option value="dark">Dark</option><option value="system">Sistema</option></select></label><label><span>Escala inicial</span><select value={scale} onChange={(event) => setScale(event.target.value)}><option value="linear">Linear</option><option value="log">LogarÃ­tmica quando vÃ¡lida</option></select></label><div className="rc-check"><input id="confirm-cancel" aria-label="Confirmar cancelamento" type="checkbox" checked={confirmCancel} onChange={(event) => setConfirmCancel(event.target.checked)} /><span><strong>Confirmar cancelamento</strong><small>Evita interromper uma execuÃ§Ã£o por engano.</small></span></div></section><section className="rc-panel"><h2>Limites imutÃ¡veis</h2><dl><div><dt>Runtime mÃ¡ximo</dt><dd>30 s</dd></div><div><dt>MemÃ³ria mÃ¡xima</dt><dd>768 MiB</dd></div><div><dt>Tier pÃºblico</dt><dd>Tier 0</dd></div><div><dt>Checkpoint</dt><dd>V5</dd></div></dl><p className="rc-scope-note">Esses controles pertencem ao Resource Policy V3 e sÃ³ podem ser alterados no backend com evidÃªncia de calibraÃ§Ã£o.</p></section></div></>;
}

function RunDetails({ runId, notify }: { runId: string; notify: (message: string, tone?: Toast["tone"]) => void }) {
  const data = useRemote(() => researchApi.experiment(runId), [runId]); const [confirmCancel, setConfirmCancel] = useState(false); const [chartMetric, setChartMetric] = useState("nashConv"); const [xAxis, setXAxis] = useState<"iteration" | "runtimeMs">("iteration"); const [scale, setScale] = useState<"linear" | "log">("linear");
  const state = data.value?.summary.state;
  useEffect(() => {
    if (!state || !["preflight", "ready", "running", "cancelling"].includes(state)) return;

    return subscribeToRun(runId, { event: (event) => { if (["completed", "failed", "cancelled", "interrupted"].includes(event.state)) data.reload(); else if (event.type === "ITERATION_PROGRESS" || event.type === "CHECKPOINT_CREATED") data.reload(); }, error: () => { window.setTimeout(data.reload, 500); } });
  // reload is revision-based and intentionally omitted to avoid reconnecting after every event.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [runId, state]);
  const action = async (name: "run" | "checkpoint" | "resume" | "verify" | "cancel") => { try { await researchApi.action(runId, name); notify(name === "verify" ? "Integridade do artefato confirmada." : `AÃ§Ã£o ${name} aceita pelo engine.`, "success"); setConfirmCancel(false); data.reload(); } catch (error) { notify(`${(error as ConsoleApiError).code}: ${(error as Error).message}`, "error"); } };
  if (data.loading && !data.value) return <Loading rows={8} />;
  if (data.error || !data.value) return <ErrorState error={data.error ?? new Error("ExecuÃ§Ã£o nÃ£o encontrada.")} retry={data.reload} />;
  const detail = data.value; const result = detail.result; const active = ["preflight", "ready", "running", "cancelling"].includes(detail.summary.state); const recoverable = ["cancelled", "interrupted", "failed"].includes(detail.summary.state) && detail.checkpoints.length > 0;
  const availableMetrics = result ? [...new Set(result.convergence.flatMap((row) => Object.keys(row)))].filter((key) => !["iteration", "runtimeMs"].includes(key)) : [];
  return <><SectionTitle eyebrow={`${algorithmLabel(detail.summary.algorithm)} Â· ${providerLabel(detail.summary.provider)}`} title={detail.summary.experimentId} copy={`Run ${detail.summary.runId}`} actions={<><StatusBadge state={detail.summary.state} />{active && <span className="rc-live">â— LIVE</span>}</>} />
    <div className="rc-run-actions">{detail.summary.state === "created" && <button className="rc-button rc-button-primary" onClick={() => void action("run")}>Start</button>}{detail.summary.state === "running" && <button className="rc-button rc-button-ghost" onClick={() => void action("checkpoint")}>Criar checkpoint</button>}{active && detail.summary.state !== "cancelling" && <button className="rc-button rc-button-danger" onClick={() => setConfirmCancel(true)}>Cancelar</button>}{recoverable && <button className="rc-button rc-button-primary" onClick={() => void action("resume")}>Retomar do checkpoint</button>}{result && <><button className="rc-button rc-button-ghost" onClick={() => void action("verify")}>Verificar integridade</button><a className="rc-button rc-button-ghost" href={researchApi.exportUrl(runId, "json")}>Exportar JSON</a><a className="rc-button rc-button-ghost" href={researchApi.exportUrl(runId, "csv")}>Exportar CSV</a></>}</div>
    <section className="rc-metric-grid"><MetricCard label="Progresso" value={`${Math.round(detail.summary.progress * 100)}%`} detail={`${detail.summary.completedIterations}/${detail.summary.iterations} iteraÃ§Ãµes`} tone={active ? "amber" : detail.summary.state === "completed" ? "green" : "default"} /><MetricCard label="Runtime" value={formatDuration(result?.metrics.runtimeMs)} detail={result ? `${Math.round(result.metrics.nodesVisited / Math.max(1, result.metrics.runtimeMs) * 1000).toLocaleString("pt-BR")} nodes/s` : "aguardando resultado"} /><MetricCard label="Peak RSS" value={formatBytes(result?.metrics.peakRssBytes)} detail="observado pelo worker" /><MetricCard label="NashConv" value={metric(result?.metrics.nashConv)} detail="menor Ã© melhor" /><MetricCard label="Exploitability" value={metric(result?.metrics.exploitability)} detail="quando calculÃ¡vel" /></section>
    <ProgressBar value={detail.summary.progress} label="Progresso da execuÃ§Ã£o" />
    {detail.status.error && <ErrorState error={detail.status.error} />}
    {result ? <><section className="rc-panel"><div className="rc-panel-head"><div><span>CONVERGENCE SERIES</span><h2>ConvergÃªncia real</h2></div><div className="rc-chart-controls"><select value={chartMetric} onChange={(event) => setChartMetric(event.target.value)}>{availableMetrics.map((key) => <option key={key}>{key}</option>)}</select><select value={xAxis} onChange={(event) => setXAxis(event.target.value as "iteration" | "runtimeMs")}><option value="iteration">IteraÃ§Ãµes</option><option value="runtimeMs">Tempo</option></select><select value={scale} onChange={(event) => setScale(event.target.value as "linear" | "log")}><option value="linear">Linear</option><option value="log">Log</option></select></div></div><ConvergenceChart metric={chartMetric} xAxis={xAxis} scale={scale} series={[{ label: algorithmLabel(detail.summary.algorithm), color: "#b9f45b", rows: result.convergence }]} /></section>
      <div className="rc-two-columns"><section className="rc-panel"><div className="rc-panel-head"><div><span>RESULT V1</span><h2>Identidade e validaÃ§Ã£o</h2></div><ValidationBadge level={result.validation.level} /></div><dl><div><dt>Artifact checksum</dt><dd><code>{result.artifactChecksum}</code></dd></div><div><dt>Structural hash</dt><dd><code>{result.compiler.structuralHash}</code></dd></div><div><dt>State hash</dt><dd><code>{result.metrics.stateHash}</code></dd></div><div><dt>Cross-check independente</dt><dd>{result.validation.independentEvaluation.performed ? result.validation.independentEvaluation.passed ? "PASS" : "FAIL" : "NÃ£o executado"}</dd></div><div><dt>Poker certificado</dt><dd>NÃ£o</dd></div></dl></section><section className="rc-panel"><div className="rc-panel-head"><div><span>CHECKPOINT HISTORY</span><h2>{detail.checkpoints.length} geraÃ§Ãµes</h2></div></div>{detail.checkpoints.length ? <ul className="rc-event-list">{detail.checkpoints.map((checkpoint) => <li key={checkpoint.file}><i className="success" /><div><strong>{checkpoint.file}</strong><span>{formatBytes(checkpoint.sizeBytes)} Â· {new Date(checkpoint.modifiedAt).toLocaleString("pt-BR")}</span></div></li>)}</ul> : <EmptyState title="Sem checkpoint" copy="Esta execuÃ§Ã£o concluiu sem produzir uma geraÃ§Ã£o persistida." />}</section></div>
    </> : <section className="rc-panel"><div className="rc-panel-head"><div><span>EVENT STREAM</span><h2>Eventos recentes</h2></div><small>SSE + replay persistido</small></div><EventList detail={detail} /></section>}
    {result && <section className="rc-panel"><div className="rc-panel-head"><div><span>PROVENANCE</span><h2>LimitaÃ§Ãµes declaradas</h2></div></div><ul className="rc-limitations">{result.limitations.map((item) => <li key={item}>{item}</li>)}</ul></section>}
    {confirmCancel && <Dialog title="Cancelar esta execuÃ§Ã£o?" destructive onClose={() => setConfirmCancel(false)} confirm={() => void action("cancel")}><p>O engine farÃ¡ cancelamento cooperativo. Um checkpoint Ã­ntegro poderÃ¡ permitir retomada; progresso apÃ³s o Ãºltimo checkpoint pode ser perdido.</p></Dialog>}
  </>;
}

function EventList({ detail }: { detail: ConsoleRunDetails }) {
  const events = detail.events.slice(-12).reverse();
  return events.length ? <ul className="rc-event-list">{events.map((event) => <li key={`${event.sequence}-${event.type}`}><i className={event.type.includes("FAILED") ? "danger" : event.type.includes("COMPLETED") || event.type.includes("PASSED") ? "success" : ""} /><div><strong>{event.type.replaceAll("_", " ")}</strong><span>{event.message}</span></div><time>{new Date(event.timestamp).toLocaleTimeString("pt-BR")}</time></li>)}</ul> : <EmptyState title="Sem eventos" copy="O primeiro evento aparecerÃ¡ apÃ³s a criaÃ§Ã£o da execuÃ§Ã£o." />;
}

function AppView({ path, navigate, notify }: { path: PathState; navigate: (path: string) => void; notify: (message: string, tone?: Toast["tone"]) => void }) {
  if (path.id && (path.section === "experiments" || path.section === "results")) return <RunDetails runId={path.id} notify={notify} />;
  if (path.section === "experiments") return <Experiments />;
  if (path.section === "new") return <NewExperiment navigate={navigate} notify={notify} />;
  if (path.section === "algorithms") return <Algorithms />;
  if (path.section === "games") return <GameExplorer />;
  if (path.section === "results") return <Results />;
  if (path.section === "checkpoints") return <Checkpoints />;
  if (path.section === "diagnostics") return <Diagnostics />;
  if (path.section === "settings") return <Settings />;
  return <Overview />;
}

export function ResearchConsole({ initialPath }: { initialPath: string[] }) {
  const [path, setPath] = useState(() => parsePath(initialPath)); const [menu, setMenu] = useState(false); const [connected, setConnected] = useState<"checking" | "online" | "offline">("checking"); const [toasts, setToasts] = useState<Toast[]>([]);
  const notify = useCallback((message: string, tone: Toast["tone"] = "info") => { const id = Date.now() + Math.random(); setToasts((items) => [...items, { id, message, tone }]); window.setTimeout(() => setToasts((items) => items.filter((item) => item.id !== id)), 4500); }, []);
  const navigate = useCallback((target: string) => { window.history.pushState({}, "", target); const parts = target.replace(/^\/research\/?/, "").split("/").filter(Boolean); setPath(parsePath(parts)); setMenu(false); window.scrollTo({ top: 0, behavior: "smooth" }); }, []);
  useEffect(() => { const pop = () => setPath(parsePath(window.location.pathname.replace(/^\/research\/?/, "").split("/").filter(Boolean))); window.addEventListener("popstate", pop); return () => window.removeEventListener("popstate", pop); }, []);
  useEffect(() => { let active = true; const check = () => void researchApi.health().then(() => active && setConnected("online")).catch(() => active && setConnected("offline")); check(); const timer = window.setInterval(check, 10_000); return () => { active = false; window.clearInterval(timer); }; }, []);
  const link = (target: string, label: string, icon: string) => <Link key={target} className={path.section === target ? "active" : ""} href={target === "overview" ? "/research" : `/research/${target}`} onClick={(event) => { event.preventDefault(); navigate(target === "overview" ? "/research" : `/research/${target}`); }}><i>{icon}</i><span>{label}</span></Link>;
  return <main className="rc-shell"><aside className={`rc-sidebar ${menu ? "open" : ""}`}><Link className="rc-brand" href="/research" onClick={(event) => { event.preventDefault(); navigate("/research"); }}><span className="rc-brand-mark">P</span><span><strong>Preflop Lab</strong><small>Research Console</small></span></Link><nav aria-label="NavegaÃ§Ã£o do Research Console">{NAVIGATION.slice(0, 3).map(([key, label, icon]) => link(key, label, icon))}<div className="rc-nav-label">RESEARCH</div>{NAVIGATION.slice(3, 7).map(([key, label, icon]) => link(key, label, icon))}<div className="rc-nav-label">SYSTEM</div>{NAVIGATION.slice(7).map(([key, label, icon]) => link(key, label, icon))}</nav><div className="rc-sidebar-foot"><Link href="/">â† Voltar ao Trainer</Link><div><span className={`rc-connection rc-connection-${connected}`} />{connected === "online" ? "Engine online" : connected === "offline" ? "Engine offline" : "Verificandoâ€¦"}</div><small>v1.0.0 Â· synthetic scope</small></div></aside><div className="rc-main"><header className="rc-topbar"><button className="rc-menu" onClick={() => setMenu((value) => !value)} aria-label="Abrir navegaÃ§Ã£o" aria-expanded={menu}>â˜°</button><div><span className="rc-breadcrumb">RESEARCH CONSOLE</span><strong>{NAVIGATION.find(([key]) => key === path.section)?.[1] ?? "Overview"}</strong></div><div className="rc-top-actions"><span className={`rc-engine-state ${connected}`}>{connected === "online" ? "â— ENGINE CONNECTED" : connected === "offline" ? "â—‹ ENGINE OFFLINE" : "â—Œ CHECKING"}</span><Link href="/research/new" onClick={(event) => { event.preventDefault(); navigate("/research/new"); }}>+ NEW RUN</Link></div></header>{menu && <button className="rc-mobile-scrim" aria-label="Fechar navegaÃ§Ã£o" onClick={() => setMenu(false)} />}<div className="rc-content"><AppView path={path} navigate={navigate} notify={notify} /></div></div><Toasts items={toasts} dismiss={(id) => setToasts((items) => items.filter((item) => item.id !== id))} /></main>;
}
