"use client";

import { useState } from "react";
import { SCENARIOS, type Position, type ScenarioKey } from "../core/domain";
import { defaultQuery, strategyRepository } from "../core/strategy-data";
import { StrategyMatrix } from "../components/strategy-matrix";
import { PositionExpansionLab } from "../components/academy-interactive";

type Lesson = {
  id: string;
  chapter: string;
  title: string;
  summary: string;
  theory: string[];
  takeaway: string;
  example: { hand: string; node: string; explanation: string };
  practice: { scenario: ScenarioKey; hero: Position; stack: number };
  question: string;
  options: string[];
  correct: number;
  answer: string;
};

const LESSONS: Lesson[] = [
  { id: "foundations", chapter: "01 · FOUNDATIONS", title: "Como pensar em ranges", summary: "Combos, posições, stack efetivo, frequências e EV.", theory: ["Uma decisão preflop pertence a um range: o conjunto de todas as mãos que chegam ao mesmo node.", "Posição determina quantos jogadores ainda podem reagir. Stack efetivo determina quanto pode ser ganho ou perdido.", "Estratégia pura usa a mesma ação sempre; estratégia mista distribui ações em frequências."], takeaway: "Leia cada mão como parte de uma região, nunca como uma regra isolada.", example: { hand: "A5s", node: "BTN RFI 40bb", explanation: "O ás bloqueia continuações fortes e o mesmo naipe preserva jogabilidade. Isso explica por que A5s pode ocupar uma região agressiva diferente de A9o." }, practice: { scenario: "rfi", hero: "BTN", stack: 40 }, question: "Ao comparar duas mãos próximas, o que melhor revela uma fronteira?", options: ["O valor nominal da carta mais alta", "A mudança de ação e frequência entre vizinhas", "A última mão vista no treino"], correct: 1, answer: "Fronteiras aparecem onde a ação dominante ou sua frequência muda entre mãos estruturalmente próximas." },
  { id: "rfi", chapter: "02 · RFI", title: "Construção de ranges de open", summary: "Como posição e stack expandem ou comprimem o primeiro range agressor.", theory: ["UTG enfrenta sete jogadores e precisa abrir um range mais forte. BTN enfrenta apenas os blinds e pode disputar mais potes.", "Pares, broadways e ases suited formam regiões com funções diferentes. A fronteira offsuit muda bastante por posição.", "Stacks curtos alteram o valor de mãos que realizam equidade mal depois do flop e introduzem jams."], takeaway: "Quanto menos jogadores restam, maior a liberdade para abrir — mas a construção ainda precisa suportar reações.", example: { hand: "K8o", node: "CO vs BTN RFI", explanation: "A mesma mão pode ser fold no CO e entrar no BTN porque há menos ranges atrás e mais chance de ganhar os blinds." }, practice: { scenario: "rfi", hero: "CO", stack: 40 }, question: "Por que o BTN abre mais mãos que UTG?", options: ["Porque recebe cartas melhores", "Porque há menos jogadores para reagir e terá posição pós-flop", "Porque paga menos ante"], correct: 1, answer: "Menos ranges atrás e vantagem posicional aumentam a realização de equidade e o fold equity do open." },
  { id: "vs-rfi", chapter: "03 · PLAYING VS RFI", title: "Defender, pagar ou 3-betar", summary: "Interação entre o range do opener, posição e construção linear/polar.", theory: ["Contra posições iniciais, o range adversário é forte e sua continuação precisa ser mais seletiva.", "Em posição, calls realizam mais equidade. Fora de posição, mãos marginais perdem valor e parte do range migra para 3-bet ou fold.", "Blockers ajudam a escolher bluffs agressivos, mas não transformam qualquer Ax em continuação."], takeaway: "Blocker é uma vantagem parcial; dominação, posição e realização de equidade continuam importando.", example: { hand: "A2o", node: "BB vs UTG+1", explanation: "O ás remove algumas combinações de AA/AK, mas A2o continua dominado por Ax melhores e joga fora de posição. O desconto do BB não resolve esses problemas." }, practice: { scenario: "vs-open", hero: "BTN", stack: 40 }, question: "O que um blocker de ás realmente faz?", options: ["Garante que o call seja lucrativo", "Reduz algumas combinações fortes no range adversário", "Elimina a desvantagem posicional"], correct: 1, answer: "O blocker reduz combos específicos; ele não garante equidade suficiente nem melhora a posição." },
  { id: "bb-defense", chapter: "04 · BB DEFENSE", title: "Preço não é tudo", summary: "Pot odds, realização de equidade e desvantagem posicional.", theory: ["O BB já investiu 1bb e por isso recebe um preço melhor para continuar.", "Esse desconto permite defender mais mãos, mas jogar fora de posição reduz quanto da equidade teórica vira resultado.", "Suitedness, conectividade e ausência de dominação ajudam mãos marginais a realizar equidade."], takeaway: "Defenda pelo conjunto preço + equidade + realização, não apenas porque já existe 1bb no pote.", example: { hand: "T7s", node: "BB vs BTN 2.1x", explanation: "Suitedness e conectividade tornam T7s mais capaz de realizar equidade que uma mão offsuit desconectada de força parecida." }, practice: { scenario: "bb-defense", hero: "BB", stack: 40 }, question: "Por que duas mãos com equidade bruta parecida podem defender diferente?", options: ["Porque naipes não importam", "Porque realizam equidade de formas diferentes", "Porque o pote muda entre as mãos"], correct: 1, answer: "Jogabilidade, dominação e posição alteram a realização da mesma equidade bruta." },
  { id: "threebet", chapter: "05 · 3BET POTS", title: "Continuando contra 3-bets", summary: "Value, calls, 4-bets e folds dentro de uma resposta coerente.", theory: ["Uma 3-bet concentra o range adversário e aumenta o preço da continuação.", "Mãos que bloqueiam o topo podem aparecer na região agressiva, enquanto mãos com boa realização podem pagar.", "O stack muda profundamente a separação entre call, 4-bet pequena e jam."], takeaway: "A resposta deve proteger o range de open sem continuar mãos dominadas em excesso.", example: { hand: "AQs", node: "CO vs BTN 3-bet", explanation: "AQs combina força, blockers e boa realização; sua mistura depende do stack, sizing e composição do range de 3-bet." }, practice: { scenario: "vs-3bet", hero: "CO", stack: 40 }, question: "Por que não responder à 3-bet apenas com mãos premium?", options: ["Para evitar folds exploráveis e proteger o range de open", "Porque toda mão suited deve pagar", "Porque posição deixa de importar"], correct: 0, answer: "Continuar uma estrutura equilibrada impede que a 3-bet lucre automaticamente contra quase todo o open." },
  { id: "fourbet", chapter: "06 · 4BET STRATEGY", title: "Valor, bloqueadores e preço", summary: "Como separar calls, 4-bets e folds sem inventar polarização.", theory: ["A região de valor responde à força do 3-bettor e ao stack efetivo.", "Bluffs de 4-bet precisam de blockers úteis e capacidade de abandonar quando necessário.", "Em stacks menores, o espaço para 4-bet/fold desaparece e o jam pode absorver a região agressiva."], takeaway: "Blocker ajuda a selecionar dentro de uma região; não justifica agressão sozinho.", example: { hand: "A5s", node: "BTN vs BB 3-bet", explanation: "Quando aparece agressivamente, A5s combina blocker de ás com suitedness; a frequência exata deve vir do dataset do node." }, practice: { scenario: "vs-3bet", hero: "BTN", stack: 40 }, question: "Qual condição reduz o espaço para 4-bet/fold?", options: ["Stack efetivo curto", "Estar no botão", "Ter cartas do mesmo naipe"], correct: 0, answer: "Com menos fichas atrás, uma 4-bet já compromete grande parte do stack e o jam ganha relevância." },
  { id: "short-stack", chapter: "07 · SHORT STACK", title: "Ranges sob compressão", summary: "Como 8–25bb mudam opens, jams e realizações.", theory: ["Stacks curtos reduzem o valor implícito de mãos especulativas e aumentam a pressão imediata.", "O tamanho do open consome parcela maior do stack, alterando respostas de 3-bet e jam.", "A posição ainda importa: short stack não transforma toda mão em push."], takeaway: "Pense em proporção do stack investida, não apenas em blinds absolutos.", example: { hand: "22", node: "20bb RFI", explanation: "Pares baixos perdem parte do valor de set mining, mas podem ganhar valor como pressão direta dependendo da posição." }, practice: { scenario: "rfi", hero: "HJ", stack: 20 }, question: "O que stacks curtos fazem com mãos especulativas?", options: ["Sempre aumentam seu valor implícito", "Reduzem fichas disponíveis para realizar seu valor futuro", "Eliminam o efeito da posição"], correct: 1, answer: "Há menos fichas atrás para ganhar quando conectam forte, reduzindo parte do valor implícito." },
  { id: "push-fold", chapter: "08 · PUSH/FOLD", title: "Jams e calls disciplinados", summary: "Fold equity, equidade de call e preço do pote.", theory: ["Um jam combina a chance de todos foldarem com a equidade quando recebe call.", "Para pagar, compare o custo restante com o pote final e a equidade contra o range de jam.", "Card removal altera combinações, mas a decisão ainda depende do range completo."], takeaway: "Não pague um all-in pela força absoluta da mão; avalie preço e range.", example: { hand: "A8o", node: "BB vs BTN jam 15bb", explanation: "A8o bloqueia ases fortes, mas pode estar dominado por muitos Ax do range de jam; o preço e a largura do range decidem." }, practice: { scenario: "vs-jam", hero: "BB", stack: 15 }, question: "Qual é a pergunta central antes de pagar um jam?", options: ["Minha mão parece bonita?", "Tenho equidade suficiente contra o range para o preço recebido?", "Meu ás bloqueia AA?"], correct: 1, answer: "Pot odds e equidade contra o range inteiro determinam o call; blockers apenas modificam essa equidade." },
  { id: "bvb", chapter: "09 · BLIND VS BLIND", title: "Ranges largos, disciplina intacta", summary: "Como dois ranges forçados disputam um pote sem posições intermediárias.", theory: ["No SB, apenas o BB resta e o range inicial pode se expandir.", "O SB joga fora de posição pós-flop; isso cria espaço para limp, raise e misturas.", "O BB tem posição e desconto, mas não deve defender qualquer combinação."], takeaway: "BvB é largo porque restam dois jogadores, não porque a qualidade das mãos deixou de importar.", example: { hand: "J5s", node: "SB first-in 40bb", explanation: "Suitedness melhora a realização e pode permitir entrada, mas a divisão entre limp/raise depende da árvore." }, practice: { scenario: "bvb", hero: "SB", stack: 40 }, question: "Por que o limp pode existir no SB?", options: ["Para construir uma estratégia ampla sem inflar todo o range fora de posição", "Porque raise é proibido", "Para revelar menos cartas"], correct: 0, answer: "O limp permite entrar com muitas mãos preservando uma estrutura equilibrada fora de posição." },
  { id: "squeeze", chapter: "10 · SQUEEZES", title: "Ataque ao dinheiro morto", summary: "Como opener, caller e posição alteram a oportunidade de squeeze.", theory: ["O call adiciona fichas ao pote e costuma limitar parte do range do caller.", "O squeezer precisa atravessar dois ranges; blockers e força jogável ganham valor.", "Sizing e stack determinam quanto de fold equity é necessário."], takeaway: "Mais dinheiro morto não significa agressão automática: há dois ranges capazes de continuar.", example: { hand: "A4s", node: "SB vs CO open + BTN call", explanation: "O blocker de ás pode reduzir continuações fortes, enquanto suitedness preserva equidade quando o squeeze recebe call." }, practice: { scenario: "squeeze", hero: "SB", stack: 40 }, question: "O que diferencia um squeeze de uma 3-bet simples?", options: ["Existe um caller entre o open e sua ação", "O raise sempre é all-in", "A posição deixa de importar"], correct: 0, answer: "O caller cria dinheiro morto e um segundo range que pode responder." },
  { id: "mixed", chapter: "11 · MIXED STRATEGIES", title: "Frequência com função", summary: "Por que uma mão alterna ações e como estudar sem falsa precisão.", theory: ["Misturas aparecem quando ações têm resultados próximos dentro de uma solução.", "Elas ajudam a distribuir combinações e evitar padrões previsíveis.", "Frequências modeladas devem ser tratadas como aproximações; precisão decimal exige solve verificado."], takeaway: "Primeiro reconheça por que duas ações fazem sentido; depois calibre a frequência.", example: { hand: "A5s", node: "Vários nodes agressivos", explanation: "A5s pode alternar agressão e continuação por combinar blockers, suitedness e cobertura de boards baixos." }, practice: { scenario: "rfi", hero: "BTN", stack: 40 }, question: "Qual é a melhor primeira pergunta ao ver uma mistura?", options: ["Qual número devo decorar?", "Que funções cada ação cumpre para o range?", "Posso arredondar tudo para 100%?"], correct: 1, answer: "Entender as funções torna a frequência transferível entre nodes e evita memorização cega." },
  { id: "construction", chapter: "12 · RANGE CONSTRUCTION", title: "Linear, polar e merged", summary: "Organize regiões de valor, calls e bluffs de forma coerente.", theory: ["Ranges lineares priorizam força contínua; polarizados separam valor forte e bluffs; merged inclui valor mais amplo.", "A árvore, o sizing e a resposta adversária determinam qual geometria faz sentido.", "Uma mão não é bluff apenas por ser fraca: blockers e realização precisam justificar sua seleção."], takeaway: "A forma do range nasce da interação entre ações futuras, não de rótulos fixos.", example: { hand: "KQo", node: "3-bet em diferentes posições", explanation: "KQo pode ser valor, call ou fold conforme o range do opener, a posição e o stack; o nome da mão não define sua função." }, practice: { scenario: "vs-open", hero: "BTN", stack: 40 }, question: "O que define se um range deve ser mais polar ou linear?", options: ["A cor das cartas", "A árvore de respostas, sizing e interação dos ranges", "A preferência pessoal do jogador"], correct: 1, answer: "A estrutura ótima depende das continuações disponíveis e de como os ranges interagem." },
  { id: "advanced", chapter: "13 · ADVANCED THINKING", title: "Transferindo conhecimento", summary: "Compare stacks, sizings, vizinhos e nodes para formar modelos mentais.", theory: ["Proficiência vem de prever como uma mudança de contexto move regiões inteiras.", "Use Diff para separar mudanças significativas de ruído e Compare para enxergar tendências.", "Confiança alta com erro é uma misconception e merece prioridade maior que um chute errado."], takeaway: "O objetivo profissional é explicar a direção da mudança antes de olhar a matriz.", example: { hand: "KTo", node: "BTN RFI 20bb vs 40bb", explanation: "Compare ação dominante, frequência e vizinhas; depois formule a razão estrutural ligada ao stack." }, practice: { scenario: "rfi", hero: "BTN", stack: 20 }, question: "Qual sinal pede revisão prioritária?", options: ["Erro com alta confiança", "Acerto com baixa confiança", "Primeiro contato com um node"], correct: 0, answer: "Erro confiante revela um modelo mental incorreto — uma misconception — e tende a se repetir." },
];

export function LearnView({ onPractice }: { onPractice: (scenario: ScenarioKey, hero: Position, stack: number) => void }) {
  const [selected, setSelected] = useState(LESSONS[0].id);
  const [answer, setAnswer] = useState<number | null>(null);
  const [completed, setCompleted] = useState<string[]>(() => {
    if (typeof window === "undefined") return [];
    try { return JSON.parse(localStorage.getItem("preflop-lab-academy") ?? "[]") as string[]; } catch { return []; }
  });
  const lesson = LESSONS.find((item) => item.id === selected) ?? LESSONS[0];
  const lookup = strategyRepository.lookup(defaultQuery(lesson.practice));
  const complete = () => {
    const next = [...new Set([...completed, lesson.id])];
    setCompleted(next);
    localStorage.setItem("preflop-lab-academy", JSON.stringify(next));
    void fetch("/api/user-data", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ operation: "academy", data: { lessonId: lesson.id, status: "learning", mastery: 20, attempts: 1 } }) });
  };
  return <section className="academy-page">
    <aside className="academy-sidebar"><div><span>PREFLOP ACADEMY</span><b>{completed.length}/{LESSONS.length}</b></div><i><em style={{ width: `${completed.length / LESSONS.length * 100}%` }} /></i>
      <nav>{LESSONS.map((item) => <button key={item.id} className={selected === item.id ? "active" : ""} onClick={() => { setSelected(item.id); setAnswer(null); }}><span>{completed.includes(item.id) ? "✓" : item.chapter.slice(0, 2)}</span><div><small>{item.chapter}</small><b>{item.title}</b></div></button>)}</nav>
    </aside>
    <article className="lesson-view">
      <header><span>{lesson.chapter}</span><h1>{lesson.title}</h1><p>{lesson.summary}</p></header>
      <section className="theory-card"><small>THEORY</small>{lesson.theory.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}<blockquote>{lesson.takeaway}</blockquote></section>
      <section className="lesson-example"><div><small>EXEMPLO NO RANGE</small><span className="hand-chip large">{lesson.example.hand}</span><h2>{lesson.example.node}</h2><p>{lesson.example.explanation}</p></div>{lookup.status === "available" && <StrategyMatrix node={lookup.node} selectedHand={lesson.example.hand} compact />}</section>
      {lesson.id === "rfi" && <PositionExpansionLab />}
      <section className="mini-test"><small>MINI TEST</small><h2>{lesson.question}</h2><div>{lesson.options.map((option, index) => <button key={option} disabled={answer !== null} className={answer !== null ? index === lesson.correct ? "correct" : index === answer ? "wrong" : "" : ""} onClick={() => setAnswer(index)}>{option}</button>)}</div>
        {answer !== null && <p><b>{answer === lesson.correct ? "Boa." : "Revise o princípio."}</b> {lesson.answer}</p>}
      </section>
      <footer><button onClick={() => onPractice(lesson.practice.scenario, lesson.practice.hero, lesson.practice.stack)}>Praticar este conceito · {SCENARIOS[lesson.practice.scenario].short}</button><button className={completed.includes(lesson.id) ? "completed" : ""} onClick={complete}>{completed.includes(lesson.id) ? "✓ Aula concluída" : "Marcar como concluída"}</button></footer>
    </article>
  </section>;
}
